name: mediator

services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        environment:
            - ENV=development
        ports:
            - "8002:8002"
        env_file:
            - .env
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
