version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - poetry install

  dev:
    desc: Run the application locally in development mode
    cmds:
      - poetry run uvicorn main:app --reload --port 8002

  docker-up-dev:
    desc: Run the application with Docker Compose (Development)
    cmds:
      - docker compose -f {{.ROOT_DIR}}/docker-compose.yml up -d --build --wait

  docker-up-prod:
    desc: Run the application with Docker Compose (Production)
    cmds:
      - docker compose -f {{.ROOT_DIR}}/docker-compose.prod.yml up -d --build --wait

  format:
    desc: Format Python code using black and ruff
    cmds:
      - poetry run black .
      - poetry run ruff check --fix .

  lint:
    desc: Lint Python code using ruff
    cmds:
      - poetry run ruff check .

  test-e2e:
    desc: Run the E2E negotiation and transfer test
    deps: [install, docker-up-dev]
    cmds:
      - poetry run python scripts/run_e2e.py {{.CLI_ARGS}}
